### ISSUE TITLE
How do I add more languages?

### ISSUE THREAD

**Issue by rrthomas** [RubixDev/syntastica#7]
The docs sort of imply that one could add more languages, but it's not obvious how; there is also an exhaustive list of supported languages, implying that it's not possible.

Can I use my own tree-sitter highlighters with syntastica?

**Comment by RubixDev** [comment]
The main syntastica logic is generic over a [`LanguageSet`](https://rubixdev.github.io/syntastica/syntastica/language_set/trait.LanguageSet.html) which is responsible for providing the languages. There are [three official parser collections](https://rubixdev.github.io/syntastica/syntastica/#parser-collections), each providing a type implementing `LanguageSet` and based on [the same list of languages](https://github.com/RubixDev/syntastica/blob/main/syntastica-macros/languages.toml). To use other languages, you must define a language set type yourself which provides [`HighlightConfiguration`](https://rubixdev.github.io/syntastica/syntastica/language_set/struct.HighlightConfiguration.html)s from whatever source you have. I have added the [`custom_languages` example](https://github.com/RubixDev/syntastica/blob/main/examples/custom_languages.rs) which does exactly that and wraps around the [`syntastica_parsers::LanguageSetImpl`](https://rubixdev.github.io/syntastica/syntastica_parsers/struct.LanguageSetImpl.html) to keep the languages from that available. I have also made the query pre-processing logic available as [a separate crate](https://crates.io/crates/syntastica-query-preprocessor) to make using Neovim queries easier.

**Comment by rrthomas** [comment]
Thanks, that's absolutely fantastic!

**Comment by RubixDev** [comment]
If the language(s) you want to add could also be useful for other users, please also consider creating a PR to add it to the official parser collections.

**Comment by rrthomas** [comment]
Thanks, will do!
